### ISSUE TITLE
投稿が1つもない状態でテストを走らせるとエラーが起きる

### ISSUE THREAD

**Issue by muraikenta** [anycloud-inc/simple-sns-test#21]
https://github.com/anycloud-inc/simple-sns-test/blob/082ab2bef7150fa0f200817b3c6a969b926c3d18/test/features/create-post.test.ts#L11

ここで起きる

**Comment by KazutakaShimizu** [comment]
あ、なおしとくわ

**Comment by muraikenta** [comment]
あ、こっちの手元で直してる！
